# Generated by Django 2.1 on 2018-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaggit', '0002_taggeditem_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='value',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Tag Value'),
        ),
    ]
