# Generated by Django 2.2.4 on 2019-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaggit', '0004_auto_20181009_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='comment',
            field=models.TextField(blank=True, default=None, help_text='Optional Comment for Tag', null=True, verbose_name='Tag Comment'),
        ),
    ]
