# Generated by Django 2.2.4 on 2019-09-10 05:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaggit', '0005_taggeditem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True, default=None, help_text='Optional Comment for Tag', null=True, verbose_name='Tag Comment'),
        ),
    ]
